pyr_sn:
  class: 'SnCalibrator'
  output_tag: 'pyr3.0_slope_null_ri'           # Output filename
  overwrite: false
  inputs:
    in_slopes: 'pyr_slopes.out_slopes'

pyr_override:
  # mod_amp: 0.5
  # pup_diam: 16.0
  # pup_dist: 20.0
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

pyr_slopes_override:
  slopes_from_intensity: true
  # pupdata_object: 'pyr_pupdata_16x16'

main_override:
  total_time: 0.000588

# Disable noise for clean measurements
ocam_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

# data_store_override:
#   store_dir:         '/raid1/mmenessini/git/SPECULA/config/ErrorBudget/slopenulls'             # Data result directory: 'store_dir'/TN/
#   inputs:
#     input_list: ['pyr3.0_frame_null-ocam.out_pixels']

# Remove closed-loop components (not needed for slope null)
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_modes', 'data_store',
        'dm','dm_mode_res','filter','psf','ef_prop','pyr_modalrec', ]