import os
import re
import numpy as np
from pathlib import Path
from typing import List, Dict, Optional, Union, Tuple
import yaml
from astropy.io import fits

from specula.simul import Simul
from specula.data_objects.source import Source
from specula.processing_objects.data_store import DataStore
from specula.processing_objects.data_source import DataSource
from specula.calib_manager import CalibManager

def generate_field_filename(tracking_number: str,
                             analysis_type: str,
                             polar_coordinates: np.ndarray,
                             **kwargs) -> str:
    """
    Generate standardized filename for field analysis
    
    Args:
        tracking_number: Simulation tracking number
        analysis_type: Analysis type ('psf', 'modal', 'cube')
        polar_coordinates: Polar coordinates of sources
        **kwargs: Additional parameters (wavelength, sampling, etc.)
    """
    coords = np.atleast_2d(polar_coordinates)
    if coords.shape[0] == 2:
        coords = coords.T

    coords_str = "_".join([f"r{r:.1f}t{t:.1f}" for r, t in coords])

    filename = f"{tracking_number}_{analysis_type}_{coords_str}"

    # Add specific parameters
    for key, value in kwargs.items():
        if value is not None:
            if key == 'wavelength_nm':
                filename += f"_wl{value:.0f}nm"
            elif key == 'psf_sampling':
                filename += f"_samp{value}"
            elif key == 'start_time':
                filename += f"_t{value:.1f}"
            elif key == 'end_time':
                filename += f"to{value:.1f}"
            else:
                filename += f"_{key}{value}"

    return filename + ".fits"


def check_simulation_data_completeness(tn_dir: Path) -> Dict[str, any]:
    """
    Check if all required data for a tracking number is available
    
    Returns:
        Dict with status of completeness, missing files, and available data
    """
    status = {
        'complete': True,
        'missing_files': [],
        'available_data': {},
        'dm_count': 0,
        'has_atmosphere': False,
        'has_vibrations': False,
        'has_ncpa': False,
        'dm_commands': False
    }

    # Parameters file
    params_file = tn_dir / "params.yml"
    if not params_file.exists():
        status['complete'] = False
        status['missing_files'].append("params.yml")
    else:
        status['available_data']['params'] = str(params_file)

    # DM commands
    dm_files = []
    if (tn_dir / "comm.fits").exists():
        dm_files.append("comm.fits")
        status['dm_count'] = 1
    else:
        i = 1
        while (tn_dir / f"comm{i}.fits").exists():
            dm_files.append(f"comm{i}.fits")
            i += 1
        status['dm_count'] = len(dm_files)

    if len(dm_files) == 0:
        status['complete'] = False
        status['missing_files'].append("DM command files (comm*.fits)")
        status['dm_commands'] = False
    else:
        status['available_data']['dm_commands'] = dm_files
        status['dm_commands'] = True

    # Atmospheric data are not mandatory because it is generated by AtmoEvolution

    # Optional data
    optional_files = {
        'vibrations': ['vibrations.fits', 'vib.fits'],
        'ncpa': ['ncpa.fits', 'static_aberrations.fits'],
        'disturbance': ['disturbance.fits', 'external_disturbance.fits']
    }

    for data_type, possible_files in optional_files.items():
        for filename in possible_files:
            if (tn_dir / filename).exists():
                status['available_data'][data_type] = filename
                if data_type == 'vibrations':
                    status['has_vibrations'] = True
                elif data_type == 'ncpa':
                    status['has_ncpa'] = True
                break

    return status


def find_existing_analysis_files(analysis_dir: Path, 
                                tracking_number: str,
                                analysis_type: str) -> List[Path]:
    """
    Find existing analysis files for a given tracking number
    """
    pattern = f"{tracking_number}_{analysis_type}_*.fits"
    return list(analysis_dir.glob(pattern))


def parse_analysis_filename(filename: str) -> Dict[str, any]:
    """
    Extracts parameters from an analysis filename
    
    Returns:
        Dict with extracted parameters or empty dict if not matched
    """
    # Pattern for parsing the filename
    pattern = r"(\w+)_(\w+)_(.+)\.fits"
    match = re.match(pattern, filename)

    if not match:
        return {}

    tracking_number, analysis_type, params_str = match.groups()

    info = {
        'tracking_number': tracking_number,
        'analysis_type': analysis_type,
        'raw_params': params_str
    }

    # Extract polar coordinates
    coord_pattern = r"r([\d.]+)t([\d.]+)"
    coord_matches = re.findall(coord_pattern, params_str)

    if coord_matches:
        coordinates = [(float(r), float(t)) for r, t in coord_matches]
        info['coordinates'] = coordinates
        info['distances'] = [r for r, t in coordinates]

    # Extract other parameters
    param_patterns = {
        'wavelength_nm': r"wl(\d+)nm",
        'psf_sampling': r"samp(\d+)", 
        'start_time': r"t([\d.]+)",
        'end_time': r"to([\d.]+)"
    }

    for param, pattern in param_patterns.items():
        match = re.search(pattern, params_str)
        if match:
            info[param] = float(match.group(1))

    return info


class FieldAnalyser:
    """
    Class to analyze field PSF, modal analysis, and phase cubes
    for a given tracking number in the Specula framework.
    This class replicates the functionality of the previous compute_off_axis_psf,
    compute_off_axis_modal_analysis, and compute_off_axis_cube methods,
    providing a structured way to handle field sources and their analysis.
    Attributes:
        data_dir (str): Directory containing tracking number data.
        tracking_number (str): The tracking number for the analysis.
        polar_coordinates (np.ndarray): Polar coordinates of field sources.
        wavelength_nm (float): Wavelength in nanometers.
        start_time (float): Start time for the analysis.
        end_time (Optional[float]): End time for the analysis, if applicable.
        gpu (bool): Whether to use GPU for computations.
        verbose (bool): Whether to print verbose output during processing.
    """

    def __init__(self,
                 data_dir: str,
                 tracking_number: str,
                 polar_coordinates: np.ndarray,
                 wavelength_nm: float = 750.0,
                 start_time: float = 0.1,
                 end_time: Optional[float] = None,
                 gpu: bool = True,
                 verbose: bool = False):

        self.data_dir = Path(data_dir)
        self.tracking_number = tracking_number
        self.polar_coordinates = np.atleast_2d(polar_coordinates)
        self.wavelength_nm = wavelength_nm
        self.start_time = start_time
        self.end_time = end_time
        self.gpu = gpu
        self.verbose = verbose

        # Loaded parameters
        self.params = None
        self.sources = []
        self.distances = []

        # Paths - modify to create separate directories
        self.tn_dir = self.data_dir / tracking_number
        self.base_output_dir = self.data_dir  # Base directory for analysis results
        
        # Create separate directories for each analysis type
        self.psf_output_dir = self.base_output_dir / f"{tracking_number}_PSF"
        self.modal_output_dir = self.base_output_dir / f"{tracking_number}_MA"
        self.cube_output_dir = self.base_output_dir / f"{tracking_number}_CUBE"

        # Verify that the tracking number directory exists
        if not self.tn_dir.exists():
            raise FileNotFoundError(f"Tracking number directory not found: {self.tn_dir}")

        self._load_simulation_params()
        self._setup_sources()


    def _load_simulation_params(self):
        """Load simulation parameters from tracking number"""
        params_file = self.tn_dir / "params.yml"
        if not params_file.exists():
            raise FileNotFoundError(f"Parameters file not found: {params_file}")

        with open(params_file, 'r') as f:
            self.params = yaml.safe_load(f)

    def _setup_sources(self):
        """Setup field sources"""
        if self.polar_coordinates.shape[0] == 2:
            # Format: [[r1, r2, ...], [theta1, theta2, ...]]
            n_sources = self.polar_coordinates.shape[1]
            coords = self.polar_coordinates.T
        else:
            # Format: [[r1, theta1], [r2, theta2], ...]
            n_sources = self.polar_coordinates.shape[0]
            coords = self.polar_coordinates

        for i, (r, theta) in enumerate(coords):
            source_dict = {
                'polar_coordinates': [float(r), float(theta)],
                'height': float('inf'),  # star
                'magnitude': 8,
                'wavelengthInNm': self.wavelength_nm
            }
            self.sources.append(source_dict)
            self.distances.append(r)

    def check_required_data(self) -> Dict[str, any]:
        """
        Verify that all necessary data is present for replay
        """
        return check_simulation_data_completeness(self.tn_dir)

    def _get_analysis_filename(self, analysis_type: str, source_idx: int = None, **kwargs) -> str:
        """Generate filename for analysis results"""
        if source_idx is not None:
            # Single source filename
            base_name = f"{self.tracking_number}_{analysis_type}_source_{source_idx:02d}"
            
            # Add coordinate info
            r, theta = self.polar_coordinates[source_idx] if len(self.polar_coordinates.shape) == 2 else self.polar_coordinates[:, source_idx]
            base_name += f"_r{r:.1f}t{theta:.1f}"
            
            # Add specific parameters
            if 'psf_sampling' in kwargs:
                base_name += f"_samp{kwargs['psf_sampling']}"
            if 'wavelength_nm' in kwargs:
                base_name += f"_wl{kwargs['wavelength_nm']:.0f}nm"
                
            return base_name + ".fits"
        else:
            # Original method for combined files (if needed)
            return generate_field_filename(
                self.tracking_number,
                analysis_type,
                self.polar_coordinates,
                wavelength_nm=self.wavelength_nm,
                start_time=self.start_time,
                end_time=self.end_time,
                **kwargs
            )

    def _build_replay_params_psf(self, psf_sampling: int = 7) -> dict:
        """
        Modify replay_params for field PSF calculation
        """
        # Load existing replay_params
        replay_params_file = self.tn_dir / "replay_params.yml"
        if not replay_params_file.exists():
            raise FileNotFoundError(f"Replay params not found: {replay_params_file}")

        with open(replay_params_file, 'r') as f:
            replay_params = yaml.safe_load(f)

        if self.verbose:
            print(f"Original replay_params keys: {list(replay_params.keys())}")

        # Debug: Check if main object exists
        if 'main' not in replay_params:
            raise KeyError("'main' object not found in original replay_params.yml")

        # Remove conflicting objects
        self._remove_conflicting_objects(replay_params, ['PSF','CCD','SH','ShSlopec','ModulatedPyramid',
                                                         'PyrSlopec','Modalrec','ModalAnalysis','DataStore'])

        # Add field sources to existing parameters
        self._add_field_sources_to_params(replay_params)

        # Add PSF objects for each field source
        for i, source_dict in enumerate(self.sources):
            psf_name = f'psf_field_{i}'
            replay_params[psf_name] = {
                'class': 'PSF',
                'wavelengthInNm': self.wavelength_nm,
                'nd': psf_sampling,
                'start_time': self.start_time,
                'inputs': {
                    'in_ef': f'prop.out_field_source_{i}_ef'
                },
                'outputs': ['out_psf', 'out_sr']
            }

        if self.verbose:
            print(f"Final replay_params keys: {list(replay_params.keys())}")

        return replay_params

    def _build_replay_params_modal(self, modal_params: dict) -> dict:
        """
        Modify replay_params for field modal analysis
        """
        replay_params_file = self.tn_dir / "replay_params.yml"
        with open(replay_params_file, 'r') as f:
            replay_params = yaml.safe_load(f)

        # Remove conflicting objects
        self._remove_conflicting_objects(replay_params, ['PSF','CCD','SH','ShSlopec','ModulatedPyramid',
                                                        'PyrSlopec','Modalrec','ModalAnalysis','DataStore'])

        # Add field sources to existing parameters
        self._add_field_sources_to_params(replay_params)

        # Add ModalAnalysis for each source
        for i, source_dict in enumerate(self.sources):
            modal_name = f'modal_analysis_{i}'
            replay_params[modal_name] = {
                'class': 'ModalAnalysis',
                'type_str': modal_params.get('type_str', 'zernike'),
                'nmodes': modal_params.get('nmodes', 100),
                'npixels': replay_params['main']['pixel_pupil'],
                'wavelengthInNm': self.wavelength_nm,
                'inputs': {
                    'in_ef': f'prop.out_field_source_{i}_ef'
                },
                'outputs': ['out_modes']
            }

        # Add DataStore to save results (without params saving)
        input_list = []
        for i in range(len(self.sources)):
            input_list.append(f'modal_res_{i}-modal_analysis_{i}.out_modes')

        replay_params['data_store_modal'] = {
            'class': 'DataStore', 
            'store_dir': str(self.modal_output_dir),  # Fixed: use modal_output_dir
            'data_format': 'fits',  # Add explicit format
            'inputs': {
                'input_list': input_list
            }
        }

        return replay_params

    def _build_replay_params_cube(self) -> dict:
        """
        Modify replay_params for field phase cubes
        """
        replay_params_file = self.tn_dir / "replay_params.yml"
        with open(replay_params_file, 'r') as f:
            replay_params = yaml.safe_load(f)

        # Remove conflicting objects
        self._remove_conflicting_objects(replay_params, ['PSF','CCD','SH','ShSlopec','ModulatedPyramid',
                                                        'PyrSlopec','Modalrec','ModalAnalysis','DataStore'])

        # Add field sources to existing parameters
        self._add_field_sources_to_params(replay_params)

        # Add DataStore to save phase cubes
        input_list = []
        for i in range(len(self.sources)):
            input_list.append(f'phase_cube_{i}-prop.out_field_source_{i}_ef')

        replay_params['data_store_cube'] = {
            'class': 'DataStore',
            'store_dir': str(self.cube_output_dir),  # Fixed: use cube_output_dir
            'data_format': 'fits',  # Add explicit format
            'inputs': {
                'input_list': input_list
            }
        }

        return replay_params

    def _add_field_sources_to_params(self, replay_params: dict):
        """
        Add field sources and update propagation object
        Common functionality for all analysis types
        """
        # Find the position of 'prop' in the dictionary
        keys_list = list(replay_params.keys())

        if 'prop' in keys_list:
            prop_index = keys_list.index('prop')

            # Create a new ordered dictionary
            new_params = {}

            # Add all items before 'prop'
            for key in keys_list[:prop_index]:
                new_params[key] = replay_params[key]

            # Add field sources
            for i, source_dict in enumerate(self.sources):
                source_name = f'field_source_{i}'
                new_params[source_name] = {
                    'class': 'Source',
                    'polar_coordinates': source_dict['polar_coordinates'],
                    'magnitude': source_dict['magnitude'],
                    'wavelengthInNm': source_dict['wavelengthInNm'],
                    'height': source_dict['height']
                }

            # Add 'prop' and remaining items
            for key in keys_list[prop_index:]:
                new_params[key] = replay_params[key]

            # Update propagation object to include all sources
            source_refs = []
            source_refs.extend([f'field_source_{i}' for i in range(len(self.sources))])
            new_params['prop']['source_dict_ref'] = source_refs
            
            output_list = []
            for i in range(len(self.sources)):
                output_list.append(f'out_field_source_{i}_ef')
            new_params['prop']['outputs'] = output_list

            # Replace the original dictionary content
            replay_params.clear()
            replay_params.update(new_params)

        else:
            raise KeyError("'prop' object not found in original replay_params.yml")

    def _remove_conflicting_objects(self, replay_params: dict, classes_to_remove: list):
        """
        Remove objects that would conflict with the analysis based on their class
        """
        objects_to_remove = []
        
        for obj_name, obj_config in replay_params.items():
            if isinstance(obj_config, dict) and 'class' in obj_config:
                if obj_config['class'] in classes_to_remove:
                    objects_to_remove.append(obj_name)
        
        for obj_name in objects_to_remove:
            del replay_params[obj_name]
            if self.verbose:
                print(f"Removed conflicting object: {obj_name} (class: {replay_params.get(obj_name, {}).get('class', 'unknown')})")

    def _run_simulation_with_params(self, params_dict: dict, temp_filename: str) -> Simul:
        """
        Common simulation execution logic
        """
        # Determine output directory based on analysis type
        if 'psf_field_' in str(params_dict):
            output_dir = self.psf_output_dir
        elif 'modal_analysis_' in str(params_dict):
            output_dir = self.modal_output_dir
        elif 'data_store_cube' in params_dict:
            output_dir = self.cube_output_dir
        else:
            output_dir = self.psf_output_dir  # default
        
        # Save temporary parameters
        temp_params_file = output_dir / temp_filename
        output_dir.mkdir(parents=True, exist_ok=True)

        with open(temp_params_file, 'w') as f:
            yaml.dump(params_dict, f, default_flow_style=False, sort_keys=False)

        if self.verbose:
            print(f"Computing simulation using: {temp_params_file}")

        # Execute simulation with replay
        try:
            simul = Simul(str(temp_params_file))
            simul.run()
            return simul
        except Exception as e:
            print(f"Simulation failed: {e}")
            print(f"Temp params file saved for debugging: {temp_params_file}")
            raise
        finally:
            # Cleanup temporary file (comment out for debugging)
            # temp_params_file.unlink()
            pass

    def compute_field_psf(self, psf_sampling: int = 7, save_results: bool = True, force_recompute: bool = False) -> Dict:
        """Calculate field PSF using SPECULA's replay system"""
        
        # Check if all individual PSF files exist
        all_exist = True
        for i in range(len(self.sources)):
            output_file = self.psf_output_dir / self._get_analysis_filename("psf", source_idx=i, psf_sampling=psf_sampling, wavelength_nm=self.wavelength_nm)
            if not output_file.exists():
                all_exist = False
                break
        
        if not force_recompute and all_exist:
            if self.verbose:
                print(f"Loading existing PSF results from: {self.psf_output_dir}")
            return self._load_psf_results(self.psf_output_dir, psf_sampling)

        # Verify necessary data
        data_status = self.check_required_data()
        if not data_status['dm_commands']:
            raise RuntimeError("DM command data not found - cannot compute PSF")

        if self.verbose:
            print(f"Computing field PSF for {len(self.sources)} sources...")

        # Setup replay parameters and run simulation
        replay_params = self._build_replay_params_psf(psf_sampling)
        simul = self._run_simulation_with_params(replay_params, "temp_psf_replay_params.yml")

        # Extract and save results
        results = self._extract_psf_results_from_objects(simul, psf_sampling)
        if save_results:
            self._save_psf_results(results, psf_sampling)

        return results

    def compute_modal_analysis(self, modal_params: Optional[Dict] = None, save_results: bool = True, force_recompute: bool = False) -> Dict:
        """Calculate field modal analysis using replay system"""
        if modal_params is None:
            modal_params = {'type_str': 'zernike', 'nmodes': 100}

        # Check if all individual modal files exist
        all_exist = True
        for i in range(len(self.sources)):
            output_file = self.modal_output_dir / self._get_analysis_filename("modal", source_idx=i, **modal_params, wavelength_nm=self.wavelength_nm)
            if not output_file.exists():
                all_exist = False
                break

        if not force_recompute and all_exist:
            if self.verbose:
                print(f"Loading existing modal analysis from: {self.modal_output_dir}")
            return self._load_modal_results(self.modal_output_dir, modal_params)

        if self.verbose:
            print(f"Computing field modal analysis for {len(self.sources)} sources...")

        # Setup replay parameters and run simulation
        replay_params = self._build_replay_params_modal(modal_params)
        simul = self._run_simulation_with_params(replay_params, "temp_modal_replay_params.yml")

        # Extract and save results
        results = self._extract_modal_results_from_datastore(simul, modal_params)
        if save_results:
            self._save_modal_results(results, modal_params)

        return results

    def compute_phase_cube(self, save_results: bool = True, force_recompute: bool = False) -> Dict:
        """Calculate field phase cubes using replay system"""
        
        # Check if all individual cube files exist
        all_exist = True
        for i in range(len(self.sources)):
            output_file = self.cube_output_dir / self._get_analysis_filename("cube", source_idx=i, wavelength_nm=self.wavelength_nm)
            if not output_file.exists():
                all_exist = False
                break
        
        if not force_recompute and all_exist:
            if self.verbose:
                print(f"Loading existing phase cubes from: {self.cube_output_dir}")
            return self._load_cube_results(self.cube_output_dir)

        # Verify necessary data
        data_status = self.check_required_data()
        if not data_status['dm_commands']:
            raise RuntimeError("DM command data not found - cannot compute phase cubes")

        if self.verbose:
            print(f"Computing field phase cubes for {len(self.sources)} sources...")

        # Setup replay parameters and run simulation
        replay_params = self._build_replay_params_cube()
        simul = self._run_simulation_with_params(replay_params, "temp_cube_replay_params.yml")

        # Extract and save results
        results = self._extract_cube_results_from_datastore(simul)
        if save_results:
            self._save_cube_results(results)

        return results

    def _extract_psf_results_from_objects(self, simul: Simul, psf_sampling: int) -> Dict:
        """
        Extract PSF results from simulation PSF objects
        """
        results = {
            'psf_list': [],
            'sr_list': [],
            'distances': self.distances,
            'coordinates': self.polar_coordinates,
            'wavelength_nm': self.wavelength_nm,
            'psf_sampling': psf_sampling,
            'pixel_scale': None  # Calculated later
        }

        # Extract PSF from each PSF object
        for i in range(len(self.sources)):
            psf_obj = simul.objs[f'psf_field_{i}']
            results['psf_list'].append(psf_obj.int_psf.value)
            results['sr_list'].append(psf_obj.int_sr.value)

        # Calculate pixel scale (as in PASSATA)
        main_params = simul.objs['main']
        pixel_pitch = main_params.pixel_pitch
        pixel_pupil = main_params.pixel_pupil

        # scale = wavelength[m] / (diameter[m]) * rad2arcsec * (1/psf_sampling)
        scale = (self.wavelength_nm * 1e-9) / (pixel_pitch * pixel_pupil) * 206264.8 * (1.0 / psf_sampling)
        results['pixel_scale'] = scale

        return results

    def _extract_modal_results_from_datastore(self, simul: Simul, modal_params: dict) -> Dict:
        """
        Extract modal analysis results from DataStore
        """
        data_store = simul.objs['data_store_modal']

        results = {
            'modal_coeffs': [],
            'residual_variance': [],
            'turbulence_variance': [],  # If available
            'distances': self.distances,
            'coordinates': self.polar_coordinates,
            'modal_params': modal_params,
            'wavelength_nm': self.wavelength_nm
        }

        # Extract modal coefficients for each source
        for i in range(len(self.sources)):
            modal_key = f'modal_res_{i}'
            if modal_key in data_store.storage:
                # Extract time series
                time_series = data_store.storage[modal_key]
                times = np.array(list(time_series.keys()))
                coeffs = np.array(list(time_series.values()))

                results['modal_coeffs'].append(coeffs)

                # Calculate residual variance (excluding settling time)
                if self.start_time > 0:
                    valid_idx = times >= self.start_time
                    if self.end_time:
                        valid_idx &= times <= self.end_time
                    valid_coeffs = coeffs[valid_idx]
                else:
                    valid_coeffs = coeffs

                if len(valid_coeffs) > 0:
                    residual_var = np.var(valid_coeffs, axis=0)
                    results['residual_variance'].append(residual_var)
                else:
                    results['residual_variance'].append(np.zeros(coeffs.shape[1]))

        return results

    def _extract_cube_results_from_datastore(self, simul: Simul) -> Dict:
        """
        Extract phase cubes from DataStore
        """
        data_store = simul.objs['data_store_cube']

        results = {
            'phase_cubes': [],
            'times': None,
            'distances': self.distances,
            'coordinates': self.polar_coordinates,
            'wavelength_nm': self.wavelength_nm
        }

        # Extract phase cubes for each source
        times = None
        for i in range(len(self.sources)):
            cube_key = f'phase_cube_{i}'
            if cube_key in data_store.storage:
                time_series = data_store.storage[cube_key]
                if times is None:
                    times = np.array(list(time_series.keys()))
                    results['times'] = times

                # Create 3D cube: [time, y, x] 
                phases = list(time_series.values())
                if len(phases) > 0:
                    # Extract only amplitude and phase from ElectricField
                    if hasattr(phases[0], '__len__') and len(phases[0]) == 2:
                        # If it's [amplitude, phase], take only phase
                        phase_cube = np.array([phase[1] for phase in phases])
                    else:
                        phase_cube = np.array(phases)

                    results['phase_cubes'].append(phase_cube)

        return results

    # Methods to save and load results (using FITS)

    def _save_psf_results(self, results: Dict, psf_sampling: int):
        """Save PSF results as separate files for each source"""
        # Create directory if it doesn't exist
        self.psf_output_dir.mkdir(parents=True, exist_ok=True)
        
        for i, (psf_data, sr_value) in enumerate(zip(results['psf_list'], results['sr_list'])):
            filename = self.psf_output_dir / self._get_analysis_filename("psf", source_idx=i, psf_sampling=psf_sampling, wavelength_nm=self.wavelength_nm)
            
            # Create HDU list for this source
            primary_hdu = fits.PrimaryHDU(psf_data)
            
            # Add header info
            primary_hdu.header['TN'] = self.tracking_number
            primary_hdu.header['SOURCE'] = i
            primary_hdu.header['WAVELNG'] = self.wavelength_nm
            primary_hdu.header['STARTTIME'] = self.start_time
            primary_hdu.header['SAMPLING'] = psf_sampling
            primary_hdu.header['STREHL'] = sr_value
            
            # Add coordinate info
            if len(self.polar_coordinates.shape) == 2:
                r, theta = self.polar_coordinates[i]
            else:
                r, theta = self.polar_coordinates[:, i]
            primary_hdu.header['COORD_R'] = r
            primary_hdu.header['COORD_T'] = theta
            
            if self.end_time:
                primary_hdu.header['ENDTIME'] = self.end_time
            if results.get('pixel_scale'):
                primary_hdu.header['PIXSCALE'] = results['pixel_scale']
                
            # Save single HDU
            primary_hdu.writeto(filename, overwrite=True)
            
            if self.verbose:
                print(f"PSF for source {i} saved to: {filename}")

    def _save_modal_results(self, results: Dict, modal_params: dict):
        """Save modal analysis results as separate files for each source"""
        # Create directory if it doesn't exist
        self.modal_output_dir.mkdir(parents=True, exist_ok=True)
        
        for i, (modal_coeffs, residual_var) in enumerate(zip(results['modal_coeffs'], results['residual_variance'])):
            filename = self.modal_output_dir / self._get_analysis_filename("modal", source_idx=i, **modal_params, wavelength_nm=self.wavelength_nm)
            
            # Create HDU list for this source
            primary_hdu = fits.PrimaryHDU()
            
            # Modal coefficients as primary data
            modal_hdu = fits.ImageHDU(modal_coeffs, name='MODAL_COEFFS')
            
            # Residual variance as second extension
            var_hdu = fits.ImageHDU(residual_var, name='RESIDUAL_VAR')
            
            hdul = fits.HDUList([primary_hdu, modal_hdu, var_hdu])
            
            # Add header info
            primary_hdu.header['TN'] = self.tracking_number
            primary_hdu.header['SOURCE'] = i
            primary_hdu.header['WAVELNG'] = self.wavelength_nm
            primary_hdu.header['NMODES'] = modal_params['nmodes']
            primary_hdu.header['MODTYPE'] = modal_params['type_str']
            
            # Add coordinate info
            if len(self.polar_coordinates.shape) == 2:
                r, theta = self.polar_coordinates[i]
            else:
                r, theta = self.polar_coordinates[:, i]
            primary_hdu.header['COORD_R'] = r
            primary_hdu.header['COORD_T'] = theta
            
            hdul.writeto(filename, overwrite=True)
            
            if self.verbose:
                print(f"Modal analysis for source {i} saved to: {filename}")

    def _save_cube_results(self, results: Dict):
        """Save phase cubes as separate files for each source"""
        # Create directory if it doesn't exist
        self.cube_output_dir.mkdir(parents=True, exist_ok=True)
        
        for i, phase_cube in enumerate(results['phase_cubes']):
            filename = self.cube_output_dir / self._get_analysis_filename("cube", source_idx=i, wavelength_nm=self.wavelength_nm)
            
            # Create HDU list for this source
            primary_hdu = fits.PrimaryHDU(phase_cube)
            
            # Times as second extension
            times_hdu = fits.ImageHDU(results['times'], name='TIMES')
            
            hdul = fits.HDUList([primary_hdu, times_hdu])
            
            # Add header info
            primary_hdu.header['TN'] = self.tracking_number
            primary_hdu.header['SOURCE'] = i
            primary_hdu.header['WAVELNG'] = self.wavelength_nm
            
            # Add coordinate info
            if len(self.polar_coordinates.shape) == 2:
                r, theta = self.polar_coordinates[i]
            else:
                r, theta = self.polar_coordinates[:, i]
            primary_hdu.header['COORD_R'] = r
            primary_hdu.header['COORD_T'] = theta
            
            hdul.writeto(filename, overwrite=True)
            
            if self.verbose:
                print(f"Phase cube for source {i} saved to: {filename}")

    def _load_psf_results(self, output_dir: Path, psf_sampling: int) -> Dict:
        """Load PSF results from separate files"""
        results = {
            'psf_list': [],
            'sr_list': [],
            'coordinates': self.polar_coordinates,
            'distances': self.distances,
            'wavelength_nm': self.wavelength_nm,
            'psf_sampling': psf_sampling,
            'pixel_scale': None
        }
        
        for i in range(len(self.sources)):
            filename = output_dir / self._get_analysis_filename("psf", source_idx=i, psf_sampling=psf_sampling, wavelength_nm=self.wavelength_nm)
            
            if filename.exists():
                hdul = fits.open(filename)
                results['psf_list'].append(hdul[0].data)
                results['sr_list'].append(hdul[0].header.get('STREHL', 0.0))
                
                if results['pixel_scale'] is None:
                    results['pixel_scale'] = hdul[0].header.get('PIXSCALE', None)
                
                hdul.close()
            else:
                raise FileNotFoundError(f"PSF file not found: {filename}")
        
        return results

    def _load_modal_results(self, output_dir: Path, modal_params: dict) -> Dict:
        """Load modal analysis results from separate files"""
        results = {
            'modal_coeffs': [],
            'residual_variance': [],
            'coordinates': self.polar_coordinates,
            'distances': self.distances,
            'wavelength_nm': self.wavelength_nm,
            'modal_params': modal_params
        }
        
        for i in range(len(self.sources)):
            filename = output_dir / self._get_analysis_filename("modal", source_idx=i, **modal_params, wavelength_nm=self.wavelength_nm)
            
            if filename.exists():
                hdul = fits.open(filename)
                results['modal_coeffs'].append(hdul['MODAL_COEFFS'].data)
                results['residual_variance'].append(hdul['RESIDUAL_VAR'].data)
                hdul.close()
            else:
                raise FileNotFoundError(f"Modal analysis file not found: {filename}")
        
        return results

    def _load_cube_results(self, output_dir: Path) -> Dict:
        """Load phase cubes from separate files"""
        results = {
            'phase_cubes': [],
            'times': None,
            'coordinates': self.polar_coordinates,
            'distances': self.distances,
            'wavelength_nm': self.wavelength_nm
        }
        
        for i in range(len(self.sources)):
            filename = output_dir / self._get_analysis_filename("cube", source_idx=i, wavelength_nm=self.wavelength_nm)
            
            if filename.exists():
                hdul = fits.open(filename)
                results['phase_cubes'].append(hdul[0].data)
                
                if results['times'] is None:
                    results['times'] = hdul['TIMES'].data
                
                hdul.close()
            else:
                raise FileNotFoundError(f"Phase cube file not found: {filename}")
        
        return results