pyr_sn:
  class: 'SnCalibrator'
  output_tag: 'pyr2.0_slope_null'           # Output filename
  overwrite: false
  inputs:
    in_slopes: 'pyr_slopes.out_slopes'

zwfs_sn:
  class: 'SnCalibrator'
  output_tag: 'z1.5wfs_slope_null'           # Output filename
  overwrite: false
  inputs:
    in_slopes: 'zwfs_slopes.out_slopes'

pyr_override:
  mod_amp: 2.0
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

zwfs_override:
  spot_radius_lambda: 0.75         
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

main_override:
  total_time: 0.0005

# Disable noise for clean measurements
cred1_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

ocam2_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

data_store_override:
  class:             'DataStore'
  store_dir:         './calibration/slopenulls'            # Data result directory: 'store_dir'/TN/
  inputs:
    input_list: [ 'z1.5wfs_frame-ocam2.out_pixels','pyr2.0_frame-cred1.out_pixels',]

# Remove closed-loop components (not needed for slope null)
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_mode_res', #'bootstrap', 'concat_wfs_modes', #'source_science',
        'dm','dm_mode_res','filter','psf','ef_prop','pyr_modalrec', 'zwfs_modalrec','coro_psf', ]
# remove: ['atmo', 'seeing', 'wind_direction', 'wind_speed', 'dm1','dm2',
#          'filter1',  'filter2','ef_prop','first_stage_prop', 'dm1_mode_res', 'dm2_mode_res', 
#          'cred2', 'pyr0', 'pyr0_slopes', 'coro_psf',
#            'data_store', 'psf', 'pyr_modalrec', 'pyr0_modalrec','atmo_mode_res']