# Aliasing Calibration
# ================================================

# Interaction matrix calibrator
pyr_alias:
  class:     'AliasingCalibrator'
  output_tag:    'pyr0.5_s1.0_alias'       # Output filename
  recmat_object: 'pyr0.5_1300modes_rec'
  overwrite: false                         # Overwrite existing files
  inputs:
    in_slopes:   'pyr_slopes.out_slopes'      # WFS slopes input

zwfs_alias:
  class:     'AliasingCalibrator'
  output_tag:    'z1.5wfs_s1.0_alias'            # Output IM filename
  recmat_object: 'z1.5wfs_1300modes_rec'
  overwrite: false                         # Overwrite existing files
  inputs:
    in_slopes:   'zwfs_slopes.out_slopes'      # WFS slopes input

# Override main simulation parameters
main_override:
  time_step: 0.0005
  total_time: 5.000                 # 2000 frames

################################## ATMO RESIDUAL #####################################
seeing_random:
  class:             'RandomGenerator'
  amp:               0.0                 # Variation amplitude [arcsec]
  constant:          1.0                 # Mean seeing [arcsec]
  distribution:      'UNIFORM'           # Uniform distribution in [0.9, 1.1]
  outputs: ['output']

# Random atmospheric phase generator
atmo_random:
  class:                'AtmoRandomPhase'
  simul_params_ref:     'main'
  L0:                   25               # [m] Outer scale
  source_dict_ref:      ['source_ngs']
  inputs:
    seeing: 'seeing_random.output'
    pupilstop: 'vlt_aperture'
  outputs: ['out_source_ngs_ef']

# Modal decomposition of atmospheric phase
atmo_modes:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'bmc2k_vlt_kl_inv'
  inputs:
    in_ef: 'atmo_random.out_source_ngs_ef'
  outputs: ['out_modes']


# DM applying partial correction
perfect_dm:
  class: 'DM'
  simul_params_ref:  'main'
  ifunc_object:      'bmc2k_vlt_ifunc'      # Our computed influence functions
  m2c_object:        'bmc2k_vlt_m2c'        # Modal-to-command matrix
  nmodes:            1300             # Number of controlled modes
  height:            0.0                # Ground-conjugated DM
  inputs:
    in_command: 'atmo_modes.out_modes'
  outputs: ['out_layer']

ef_prop_override:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_random.out_source_ngs_ef'    # Turbulence
    in_ef2: 'perfect_dm.out_layer'              # Partial correction
  outputs: ['out_ef']

######################################################################################

pyr_override:
  mod_amp: 0.5
  inputs: 
    in_ef: 'ef_prop.out_ef'

zwfs_override:
  spot_radius_lambda: 0.75                     # Spot RADIUS in λ/D units
  inputs: 
    in_ef: 'ef_prop.out_ef'

# Disable noise for clean measurements
cred1_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

ocam2_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

# Remove unnecessary objects during calibration
remove: ['atmo','seeing','wind_speed','wind_direction','data_store','atmo_mode_res', #'source_science',
        'dm_mode_res','filter','psf', 'coro_psf', 'dm', 'prop','pyr_modalrec', 'zwfs_modalrec'] #, 'bootstrap', 'concat_wfs_modes'
