pyr_sn:
  class: 'SnCalibrator'
  output_tag: 'pyr_slope_null'           # Output filename
  overwrite: true
  inputs:
    in_slopes: 'pyr_slopes.out_slopes'

zwfs_sn:
  class: 'SnCalibrator'
  output_tag: 'zwfs_slope_null'           # Output filename
  overwrite: true
  inputs:
    in_slopes: 'zwfs_slopes.out_slopes'

pyr_override:
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

zwfs_override:
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

main_override:
  total_time: 0.0005

# Disable noise for clean measurements
cred1_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

ocam2_override:
  photon_noise:   false                   # No photon noise
  readout_noise:  false                   # No read noise
  excess_noise:   false                   # No excess noise

data_store_override:
  class:             'DataStore'
  store_dir:         './calibration/slopenulls'            # Data result directory: 'store_dir'/TN/
  inputs:
    input_list: ['ccd1-cred1.out_pixels',
                  'ccd2-ocam2.out_pixels',]

# Remove closed-loop components (not needed for slope null)
remove: ['atmo','seeing','wind_speed','wind_direction','atmo_mode_res', #'source_science',
        'dm','dm_mode_res','filter','psf','ef_prop','pyr_modalrec','zwfs_modalrec']