# AO residual phase-screens generation
# ================================================
main:
  class:             'SimulParams'
  root_dir:          '/raid1/mmenessini/calibration/SOUL/'       # CalibManager root directory (all the data are in subdirectories)
  pixel_pupil:       160                  # Must match influence function computation
  pixel_pitch:       0.0525               # [m] Pitch of the pupil phase array
  total_time:        100.0                # [s] Total simulation running time
  time_step:         1.0                  # [s] Simulation time step
  zenithAngleInDeg:  0.0                  # [deg] Zenith observation (0 means no airmass)
  display_server:    false                # Disable for batch runs

# Atmospheric conditions
seeing:
  class:             'WaveGenerator'
  constant:          0.88                  # [arcsec]

# Natural guide star for WFS
source_ngs:
  class:             'Source'
  polar_coordinates: [0.0, 0.0]            # [arcsec, deg] On-axis NGS
  height:            .inf                  # Infinite height (star)
  magnitude:         8.0                   # R-band magnitude (bright NGS)
  wavelengthInNm:    750                   # [nm] R-band for WFS

# Telescope pupil geometry
pupilstop:
  class:             'Pupilstop'
  simul_params_ref:   'main'


# Random atmospheric phase generator
atmo_random:
  class:                'AtmoRandomPhase'
  simul_params_ref:     'main'
  L0:                   25               # [m] Outer scale
  source_dict_ref:      ['source_ngs']
  update_interval:      1 
  inputs:
    seeing:             'seeing.output'
    pupilstop:          'pupilstop'
  outputs:              ['out_source_ngs_ef']

# Modal decomposition of atmospheric phase
modal_analysis_random:
  class: 'ModalAnalysis'
  ifunc_inv_object: 'asm_kl_inv'
  nmodes: 660
  inputs:
    in_ef: 'atmo_random.out_source_ngs_ef'
  outputs: ['out_modes']

scale_random:
  class:  'BaseOperation'
  constant_mul_data: 'correction_vector_500modes_c0.90' 
  inputs:
    in_value1: 'modal_analysis_random.out_modes'
  outputs: ['out_value']

# DM applying partial correction
dm_random:
  class: 'DM'
  simul_params_ref:  'main'
  ifunc_object:      'asm_ifunc'      # Our computed influence functions
  m2c_object:        'asm_m2c'        # Modal-to-command matrix
  nmodes:            660            # Number of controlled modes
  height:            0.0                # Ground-conjugated DM
  inputs:
    in_command: 'scale_random.out_value'
  outputs: ['out_layer']

atmo_pc:
  class: 'ElectricFieldCombinator'
  inputs:
    in_ef1: 'atmo_random.out_source_ngs_ef'    # Turbulence
    in_ef2: 'dm_random.out_layer'              # Partial correction
  outputs: ['out_ef']


data_store:
  class:             'DataStore'
  store_dir:         '/raid1/mmenessini/calibration/SOUL/phasescreens'
  create_tn: false
  inputs:
    input_list: ['phase_cube-atmo_pc.out_ef']