# this is the block that generates the pupil geometry file used by the Pyramid WFS
# as a function of a single frame of the Pyramid WFS
pyr_pupdata:
  class: 'PyrPupdataCalibrator'
  thr1: 0.25
  thr2: 0.4
  display_debug: True
  output_tag:        'pyr_pupdata'
  overwrite: true
  inputs:
    in_i: 'pyr.out_i'

pyr_override:
  mod_amp:           20.0   # Modulation radius (in lambda/D units)
  inputs:
    in_ef: 'prop.out_source_ngs_ef'

main_override:
  total_time:  0.0005

# Remove unnecessary components to avoid issues and speed up the calibration
remove: ['atmo', 'seeing', 'wind_direction', 'wind_speed', 'unab_prop',
          'ocam', 'slopes', 'dm', 'modalrec', 'filter', 'ef_prop', 'dm_mode_res', 
           'data_store', 'dl_psf', 'psf', 'coro_psf', 'atmo_mode_res']